# python切片操作

- 通过slice类实现，slice(start, stop[, step])  选择范围：[start, stop) 左闭右开
索引和切片都用[],方法用()


In [34]:
L = [0,1,2,3,4,5,6,7,8,9]
print('使用 slice 类实现 :\n', L[slice(2,5,2)])
print("使用 ':' 实现: \n", L[2:5:2])

使用 slice 类实现 :
 [2, 4]
使用 ':' 实现: 
 [2, 4]


## list，tuple中的切片

- 如果第一个索引是0，还可以省略, 到最后一个也可以省略，步长默认1

In [33]:
print('起始位置为0，可以省略：',L[:3])
print('终止位置最后一个，可以省略：',L[3:])

起始位置为0，可以省略： [0, 1, 2]
终止位置最后一个，可以省略： [3, 4, 5, 6, 7, 8, 9]


- 倒数索引-1代表最后一个位置索引，-2代表倒数第二个索引

In [26]:
print('开始位置到倒数第二个：',L[:-2])
print('倒数第二个位置到最后：', L[-2:])

开始位置到倒数第二个： [0, 1, 2, 3, 4, 5, 6, 7]
倒数第二个位置到最后： [8, 9]


- 步长设置, 默认1，可以自定义

In [32]:
print('设定步长-2：', L[-1:-5:-2])
print('起始位置到终止位置步长为2：',L[::2])

设定步长-2： [9, 7]
起始位置到终止位置步长为2： [0, 2, 4, 6, 8]


## Numpy中的切片操作

### numpy中的一维数组切片
- Numpy 中多维数组的切片操作与 Python 中 list 的切片操作一样，同样由 start, stop, step 三个部分组成


In [4]:

import numpy as np

arr = np.arange(12)
print('array is:', arr)

slice_one = arr[:4]
print('slice begins at 0 and ends at 4 is:', slice_one)

slice_two = arr[7:10]
print('slice begins at 7 and ends at 10 is:', slice_two)

slice_three = arr[0:12:4]
print('slice begins at 0 and ends at 12 with step 4 is:', slice_three)




array is: [ 0  1  2  3  4  5  6  7  8  9 10 11]
slice begins at 0 and ends at 4 is: [0 1 2 3]
slice begins at 7 and ends at 10 is: [7 8 9]
slice begins at 0 and ends at 12 with step 4 is: [0 4 8]


### numpy 多维数组
- 上述例子是一维数组的例子，如果是多维数组，将不同维度上的切片操作用 逗号 分开就好了

In [7]:
import numpy as np

arr = np.arange(12).reshape((3, 4))
print ('array is:\n', arr)

slice_one = arr[1:2, 1:3]
print('first slice is:\n', slice_one)

slice_two = arr[:, ::2]
print('second slice is:\n',slice_two)


array is:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
first slice is:
 [[5 6]]
second slice is:
 [[ 0  2]
 [ 4  6]
 [ 8 10]]


## Pandas中的切片操作